events {}

http {
  server {
    listen 80;

    server_name graphql.io;
    location / {
      proxy_pass http://graphql:8080;
      add_header Access-Control-Allow-Origin "*";
      add_header Access-Control-Allow-Methods "GET, HEAD, POST, PATCH, DELETE, OPTIONS";
      add_header Access-Control-Allow-Headers "Origin, Content-Type, Accept, Authorization";

      if ($request_method = 'OPTIONS' ) {
        return 204;
      }
    }
  }

  server {
    listen 80;
    server_name pwa.io;
    location / {
      proxy_pass http://pwa;
    }
  }
}

